In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline

In [2]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\human-resources-analytics\HR_comma_sep.csv")
df.head()

,satisfaction_level,last_evaluation,number_project,average_montly_hours,time_spend_company,Work_accident,left,promotion_last_5years,Department,salary
0,0.38,0.53,2,157,3,0,1,0,sales,low
1,0.80,0.86,5,262,6,0,1,0,sales,medium
2,0.10,0.77,6,247,4,0,1,0,sales,low
3,0.92,0.85,5,259,5,0,1,0,sales,low
4,0.89,1.00,5,224,5,0,1,0,sales,low

In [3]:
X,y=df.drop('left',axis=1),df.left
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26)

In [4]:
ohe = OneHotEncoder(sparse_output= False).set_output(transform = 'pandas')
ct = make_column_transformer((ohe, make_column_selector(dtype_include=object)),
                            ('passthrough',make_column_selector(dtype_include = ['int64','float64'])),
                            verbose_feature_names_out=False)
ct=ct.set_output(transform='pandas')
scaler=StandardScaler()

In [9]:
solvers=['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
scores=[]
for s in solvers:
    lr = LogisticRegression(solver=s)
    pipe=Pipeline([("ct",ct),('Scaler',scaler),("LR",lr)])
    pipe.fit(X_train,y_train)
    pred=pipe.predict(X_test)
    scores.append([s,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['solver','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)

            solver    scores
0            lbfgs  0.792621
1        liblinear  0.792398
2        newton-cg  0.792398
3  newton-cholesky  0.792398
4              sag  0.792398
5             saga  0.792398