In [26]:
import pandas as pd 
from sklearn.linear_model import LogisticRegression  
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [4]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Image_Segmentation\Image_Segmentation.csv")
df.head()

       Class  region.centroid.col  region.centroid.row  ...  value.mean  saturation.mean  hue-mean
0  BRICKFACE                  188                  133  ...    8.444445         0.538580 -0.924817
1  BRICKFACE                  105                  139  ...    7.555555         0.532628 -0.965946
2  BRICKFACE                   34                  137  ...    7.777778         0.573633 -0.744272
3  BRICKFACE                   39                  111  ...    7.888889         0.562919 -1.175773
4  BRICKFACE                   16                  128  ...    7.111111         0.561508 -0.985811

[5 rows x 20 columns]

In [6]:
X,y=df.drop('Class',axis=1),df.Class
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [29]:
sc=StandardScaler().set_output(transform='pandas')
solvers=['lbfgs', 'newton-cg', 'newton-cholesky', 'sag', 'saga']
cs=np.linspace(.001,10,20)
scores=[]
for s in solvers:
    for c in cs  :
        lr = LogisticRegression(solver=s,C=c)
        pipe=Pipeline([('sc',sc),('lr',lr)])
        pipe.fit(X_train,y_train)
        pred=pipe.predict(X_test)
        scores.append([s,c,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['solver','C','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

             solver          C    scores
0             lbfgs  10.000000  0.936508
1             lbfgs   9.473737  0.936508
2             lbfgs   8.947474  0.936508
3             lbfgs   8.421211  0.936508
4   newton-cholesky  10.000000  0.936508
5   newton-cholesky   9.473737  0.936508
6   newton-cholesky   8.947474  0.936508
7   newton-cholesky   8.421211  0.936508
8         newton-cg  10.000000  0.936508
9         newton-cg   9.473737  0.936508
10        newton-cg   8.947474  0.936508
11        newton-cg   8.421211  0.936508
12        newton-cg   6.842421  0.920635
13        newton-cg   7.368684  0.920635
14            lbfgs   7.368684  0.920635
15        newton-cg   7.894947  0.920635
16            lbfgs   7.894947  0.920635
17            lbfgs   6.842421  0.920635
18  newton-cholesky   6.842421  0.920635
19  newton-cholesky   7.894947  0.920635

In [31]:
cs=np.linspace(.001,10,20)
scores=[]
for c in cs  :
        lr = LogisticRegression(solver='saga',C=c)        
        pipe.fit(X_train,y_train)
        pred=pipe.predict(X_test)
        scores.append([s,c,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['solver','C','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)

   solver          C    scores
0    saga   1.579789  0.904762
1    saga   5.263632  0.904762
2    saga   5.789895  0.904762
3    saga   2.632316  0.904762
4    saga   7.368684  0.904762
5    saga  10.000000  0.904762
6    saga   6.316158  0.904762
7    saga   0.001000  0.888889
8    saga   1.053526  0.888889
9    saga   0.527263  0.888889
10   saga   3.684842  0.888889
11   saga   2.106053  0.888889
12   saga   4.211105  0.888889
13   saga   4.737368  0.888889
14   saga   3.158579  0.888889
15   saga   6.842421  0.888889
16   saga   7.894947  0.888889
17   saga   8.421211  0.888889
18   saga   8.947474  0.888889
19   saga   9.473737  0.888889