In [7]:
import pandas as pd 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [8]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\student_performance\student_dataset_10000_rows.csv")
df.head()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

In [9]:
X,y=df.drop("placement_status",axis=1),df.placement_status
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [10]:
sc_xtr=sc.fit_transform(X_train)
sc_xte=sc.transform(X_test)

In [11]:
scores=[]
for k in range(1,15):
    knn=KNeighborsClassifier(n_neighbors=k)
    knn.fit(sc_xtr,y_train)
    pred=knn.predict(sc_xte)
    scores.append([k,accuracy_score(y_test,pred)])
df_score=pd.DataFrame(scores,columns=['k_value','scores'])
df_score.sort_values(by='scores',ascending=False,ignore_index=True)

    k_value    scores
0        13  0.972333
1        14  0.971667
2         8  0.971000
3        12  0.969667
4         9  0.969333
5         7  0.968667
6        11  0.968333
7        10  0.968000
8         6  0.967333
9         5  0.965333
10        3  0.962000
11        4  0.960000
12        1  0.952000
13        2  0.951000

In [12]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(sc_xtr,y_train)
pred=nb.predict(sc_xte)
accuracy_score(y_test,pred)

0.961

In [13]:
import pandas as pd 
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

In [15]:

ohe=OneHotEncoder(sparse_output=False).set_output(transform='pandas')
sc=StandardScaler().set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),('passthrough',make_column_selector(dtype_exclude=object)),verbose_feature_names_out=False)
cs=np.linspace(.001,10,20)
scores=[]
for c in tqdm(cs):
    svm = SVC(kernel='linear',C=c)
    pipe=Pipeline([('sc',sc),('svm',svm)])
    pipe.fit(X_train, y_train)
    pred = pipe.predict(X_test)
    scores.append([c,accuracy_score(y_test, pred)])

df_score=pd.DataFrame(scores,columns=['C','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)

100%|██████████| 20/20 [00:03<00:00,  5.38it/s]

            C    scores
0   10.000000  0.997667
1    1.579789  0.997333
2    2.106053  0.997333
3    1.053526  0.997333
4    7.894947  0.997333
5    8.421211  0.997333
6    5.263632  0.997333
7    3.684842  0.997333
8    6.842421  0.997333
9    7.368684  0.997333
10   6.316158  0.997333
11   5.789895  0.997333
12   8.947474  0.997333
13   9.473737  0.997333
14   4.211105  0.997000
15   4.737368  0.997000
16   2.632316  0.997000
17   3.158579  0.997000
18   0.527263  0.996333
19   0.001000  0.959333