In [2]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import PolynomialFeatures
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,root_mean_squared_error
import os
os.chdir("F:\MACHINE LEARNING\SOMETHING\Datasets")

In [6]:
pizza=pd.read_csv("pizza.csv")
x = pizza[['Promote']]
y = pizza['Sales']

In [10]:
poly=PolynomialFeatures(degree=2).set_output(transform='pandas')
X_poly=poly.fit_transform(x)
X_poly

      1  Promote  Promote^2
0   1.0     23.0      529.0
1   1.0     56.0     3136.0
2   1.0     34.0     1156.0
3   1.0     25.0      625.0
4   1.0     67.0     4489.0
5   1.0     82.0     6724.0
6   1.0     46.0     2116.0
7   1.0     14.0      196.0
8   1.0      6.0       36.0
9   1.0     47.0     2209.0
10  1.0     52.0     2704.0
11  1.0     88.0     7744.0
12  1.0     71.0     5041.0
13  1.0     78.0     6084.0
14  1.0     66.0     4356.0
15  1.0     44.0     1936.0
16  1.0     68.0     4624.0
17  1.0     90.0     8100.0
18  1.0     22.0      484.0

  Branch  Home  Automobile
0    B01   400        1200
1    B02   350         360
2    B03   600         800
3    B04   800        1800
4    B05   900        1600
5    B06   200        1000
6    B07   120         900
7    B08   340        1100
8    B09   490         900
9    B10   700         800

In [28]:
insure=pd.read_csv("insure_auto.csv")
X,y=insure.drop(columns=['Operating_Cost','Branch']),insure["Operating_Cost"]
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state=34,test_size=0.3)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

6355.110042141677

In [29]:
insure=pd.read_csv("insure_auto.csv")
X,y=insure.drop(columns=['Operating_Cost','Branch']),insure["Operating_Cost"]
poly=PolynomialFeatures(degree=2,include_bias=False).set_output(transform='pandas')
poly_X=poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(poly_X,y, random_state=34,test_size=0.3)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

6207.639845876358

In [30]:
insure=pd.read_csv("insure_auto.csv")
X,y=insure.drop(columns=['Operating_Cost','Branch']),insure["Operating_Cost"]
poly=PolynomialFeatures(degree=3,include_bias=False).set_output(transform='pandas')
poly_X=poly.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(poly_X,y, random_state=34,test_size=0.3)
lr = LinearRegression()
lr.fit(X_train,y_train)
y_pred = lr.predict(X_test)
root_mean_squared_error(y_test,y_pred)

7330.291250961744

## Boston