In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

In [2]:
df=pd.read_csv("F:\MACHINE LEARNING\SOMETHING\Datasets\Housing.csv")
dum_hous=pd.get_dummies(df,drop_first=True)
X,y=dum_hous.drop('price',axis=1),dum_hous['price']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26)
lr=LinearRegression()
lr.fit(X_train,y_train)
pred=lr.predict(X_test)
r2_score(y_test,pred)

0.6791781818067918

In [3]:
df.head()

,price,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,42000.0,5850,3,1,2,yes,no,yes,no,no,1,no
1,38500.0,4000,2,1,1,yes,no,no,no,no,0,no
2,49500.0,3060,3,1,1,yes,no,no,no,no,0,no
3,60500.0,6650,3,1,2,yes,yes,no,no,no,0,no
4,61000.0,6360,2,1,1,yes,no,no,no,no,0,no

In [4]:
X_train.head()

,lotsize,bedrooms,bathrms,stories,garagepl,driveway_yes,recroom_yes,fullbase_yes,gashw_yes,airco_yes,prefarea_yes
40,3745,3,1,2,0,True,False,True,False,False,False
197,4350,3,1,2,1,False,False,False,True,False,False
48,4960,4,1,3,0,False,False,False,False,False,False
67,6000,2,1,1,1,True,False,True,False,True,False
26,3800,2,1,1,0,True,False,False,False,False,False

In [5]:
test_data=pd.read_csv(r"F:\MACHINE LEARNING\SOMETHING\Datasets\tst_Housing.csv")
test_data.head()

,lotsize,bedrooms,bathrms,stories,driveway,recroom,fullbase,gashw,airco,garagepl,prefarea
0,5600,3,1,2,yes,no,yes,no,no,1,no
1,4355,2,1,1,yes,no,no,no,no,0,no
2,3412,3,1,1,yes,no,no,no,no,0,no
3,6666,2,2,2,yes,yes,no,no,no,0,no