In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.compose import make_column_selector,make_column_transformer

In [2]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\human-resources-analytics\HR_comma_sep.csv")
df.head()

   satisfaction_level  last_evaluation  number_project  ...  promotion_last_5years  Department  salary
0                0.38             0.53               2  ...                      0       sales     low
1                0.80             0.86               5  ...                      0       sales  medium
2                0.10             0.77               6  ...                      0       sales     low
3                0.92             0.85               5  ...                      0       sales     low
4                0.89             1.00               5  ...                      0       sales     low

[5 rows x 10 columns]

In [4]:
X,y=df.drop('left',axis=1),df.left
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26)

In [6]:
ohe = OneHotEncoder(sparse_output= False).set_output(transform = 'pandas')
ct = make_column_transformer((ohe, make_column_selector(dtype_include=object)),
                            ('passthrough',make_column_selector(dtype_include = ['int64','float64'])),
                            verbose_feature_names_out=False)
ct=ct.set_output(transform='pandas')
scaler=StandardScaler()

In [10]:
from sklearn.pipeline import Pipeline
ks=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
scores=[]
for k in ks:
    knn=KNeighborsClassifier(n_neighbors=k)
    pipe=Pipeline([("ct",ct),('Scaler',scaler),("KNN",knn)])
    pipe.fit(X_train,y_train)
    pred=pipe.predict(X_test)
    scores.append([k,accuracy_score(y_test,pred)])
df_score=pd.DataFrame(scores,columns=['K','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)

     K    scores
0    1  0.957991
1    2  0.955101
2    4  0.946210
3    3  0.945099
4    6  0.943765
5    8  0.939542
6    5  0.938431
7   10  0.937319
8    7  0.936875
9    9  0.935541
10  12  0.935541
11  14  0.934430
12  11  0.933985
13  13  0.933319
14  16  0.931318
15  15  0.930651