In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve,roc_auc_score,RocCurveDisplay
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from tqdm import tqdm

In [12]:
df= pd.read_csv(r"F:\MACHINE LEARNING\SOMETHING\Cases\Kyphosis\Kyphosis.csv")
X,y=df.drop('Kyphosis',axis=1),df['Kyphosis']

df.head()

  Kyphosis  Age  Number  Start
0   absent   71       3      5
1   absent  158       3     14
2  present  128       4      5
3   absent    2       5      1
4   absent    1       4     15

In [14]:
le=LabelEncoder()
y=le.fit_transform(y)
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=.3,stratify=y)

In [17]:
gbm=GradientBoostingClassifier(random_state=26)
gbm.fit(X_train,y_train)
y_pred_prob=gbm.predict_proba(X_test)
roc_auc_score(y_test,y_pred_prob[:,1])

0.45999999999999996

In [22]:
rates=np.linspace(.01,.9,10)
depth=[None,2,3,4]
n_est=[25,50,100]
scores=[]
for r in tqdm(rates):
    for n in n_est:
        for d in depth:
            gdm=GradientBoostingClassifier(random_state=26,
                                          max_depth=d,n_estimators=n,
                                          learning_rate=r)
            gdm.fit(X_train,y_train)
            y_pred_prob=gdm.predict_proba(X_test)
            scores.append([r,n,d,roc_auc_score(y_test,y_pred_prob[:,1])])
df_scores = pd.DataFrame(scores, columns= ['rates','n_est','depth','roc'])
df_scores.sort_values('roc', ascending = False, ignore_index= True)[:20]

100%|██████████| 10/10 [00:08<00:00,  1.22it/s]

       rates  n_est  depth    roc
0   0.010000     25    2.0  0.830
1   0.010000     50    2.0  0.805
2   0.010000    100    2.0  0.785
3   0.702222     25    2.0  0.705
4   0.603333     25    2.0  0.700
5   0.702222     50    2.0  0.695
6   0.108889     50    2.0  0.670
7   0.207778     25    2.0  0.670
8   0.801111     50    2.0  0.665
9   0.603333     50    2.0  0.660
10  0.900000     50    4.0  0.660
11  0.900000    100    4.0  0.660
12  0.108889     25    2.0  0.660
13  0.801111     25    2.0  0.655
14  0.900000     25    2.0  0.650
15  0.900000     25    4.0  0.650
16  0.306667     25    2.0  0.650
17  0.900000     50    2.0  0.640
18  0.504444     25    2.0  0.640
19  0.108889    100    2.0  0.640