In [10]:
from sklearnex import patch_sklearn
patch_sklearn()
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from sklearn.metrics import accuracy_score, r2_score
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, GradientBoostingRegressor
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
from tqdm import tqdm

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)

In [11]:
hr = pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\human-resources-analytics\HR_comma_sep.csv")
X,y=hr.drop('left',axis=1),hr['left']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=.3,stratify=y)
hr.head()

   satisfaction_level  last_evaluation  number_project  ...  promotion_last_5years  Department  salary
0                0.38             0.53               2  ...                      0       sales     low
1                0.80             0.86               5  ...                      0       sales  medium
2                0.10             0.77               6  ...                      0       sales     low
3                0.92             0.85               5  ...                      0       sales     low
4                0.89             1.00               5  ...                      0       sales     low

[5 rows x 10 columns]

In [12]:
ohe=OneHotEncoder(sparse_output=False,drop='first').set_output(transform='pandas')
ct=make_column_transformer((ohe,make_column_selector(dtype_include=object)),
                           ('passthrough',make_column_selector(dtype_exclude=object)), verbose_feature_names_out=False ).set_output(transform='pandas')
ct=ct.set_output(transform='pandas')
ct_ohe_tr=ct.fit_transform(X_train)
ct_ohe_tst=ct.transform(X_test)

In [13]:

learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = GradientBoostingClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n)
            gbm.fit(ct_ohe_tr, y_train)
            pred = gbm.predict(ct_ohe_tst)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

Extension for Scikit-learn* enabled (https://github.com/uxlfoundation/scikit-learn-intelex)
100%|██████████| 10/10 [02:02<00:00, 12.26s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.603333        4.0           100         0.987553
1        0.504444        4.0           100         0.985552
2        0.603333        4.0            50         0.983774
3        0.010000        NaN            50         0.983552
4        0.405556        4.0           100         0.983330
5        0.306667        4.0           100         0.982663
6        0.801111        4.0           100         0.982663
7        0.702222        3.0           100         0.982218
8        0.801111        4.0            50         0.982218
9        0.207778        4.0           100         0.981551
10       0.010000        NaN           100         0.981329
11       0.405556        4.0            50         0.981107
12       0.207778        NaN           100         0.980218
13       0.801111        3.0           100         0.979996
14       0.900000        3.0           100         0.979996
15       0.504444        4.0            50         0.979773
16       0.603333        4.0            25         0.979551
17       0.207778        NaN            25         0.979551
18       0.108889        NaN            25         0.979551
19       0.405556        4.0            25         0.979329

In [9]:
pip install xgboost

Collecting xgboost
  Downloading xgboost-3.4.1-py3-none-win_amd64.whl.metadata (2.0 kB)
Requirement already satisfied: numpy in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from xgboost) (1.18.0)
Downloading xgboost-3.4.1-py3-none-win_amd64.whl (48.9 MB)
   ---------------------------------------- 0.0/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.3/48.9 MB ? eta -:--:--
   ---------------------------------------- 0.5/48.9 MB 1.1 MB/s eta 0:00:43
   ---------------------------------------- 0.5/48.9 MB 1.1 MB/s eta 0:00:43
    --------------------------------------- 0.8/48.9 MB 1.1 MB/s eta 0:00:43
    --------------------------------------- 1.0/48.9 MB 1.1 MB/s eta 0:00:42
   - -------------------------------------- 1.3/48.9 MB 1.2 MB/s eta 0:00:40
   - -------------------------------------- 1.6/48.9 MB 1.1 MB/s eta 0:00:42
   - -------------------------------------- 1.6/48.9 MB 1.1 MB/s eta 0:00:42
   - -------------------------------------- 1.8/48.9 MB 1.0 MB/s eta 0:00:47
   - -------------------------------------- 1.8/48.9 MB 1.0 MB/s eta 0:00:47
   - -------------------------------------- 2.1/48.9 MB 905.4 kB/s eta 0:00:52
   - -------------------------------------- 2.1/48.9 MB 905.4 kB/s eta 0:00:52
   - -------------------------------------- 2.4/48.9 MB 902.6 kB/s eta 0:00:52
   -- ------------------------------------- 2.6/48.9 MB 882.7 kB/s eta 0:00:53
   -- ------------------------------------- 2.6/48.9 MB 882.7 kB/s eta 0:00:53
   -- ------------------------------------- 2.6/48.9 MB 882.7 kB/s eta 0:00:53
   -- ------------------------------------- 2.9/48.9 MB 810.3 kB/s eta 0:00:57
   -- ------------------------------------- 3.1/48.9 MB 822.0 kB/s eta 0:00:56
   -- ------------------------------------- 3.4/48.9 MB 852.6 kB/s eta 0:00:54
   -- ------------------------------------- 3.7/48.9 MB 880.1 kB/s eta 0:00:52
   --- ------------------------------------ 3.9/48.9 MB 894.0 kB/s eta 0:00:51
   --- ------------------------------------ 4.2/48.9 MB 912.0 kB/s eta 0:00:50
   --- ------------------------------------ 4.5/48.9 MB 924.2 kB/s eta 0:00:49
   --- ------------------------------------ 4.5/48.9 MB 924.2 kB/s eta 0:00:49
   --- ------------------------------------ 4.7/48.9 MB 904.2 kB/s eta 0:00:49
   --- ------------------------------------ 4.7/48.9 MB 904.2 kB/s eta 0:00:49
   ---- ----------------------------------- 5.0/48.9 MB 870.5 kB/s eta 0:00:51
   ---- ----------------------------------- 5.0/48.9 MB 870.5 kB/s eta 0:00:51
   ---- ----------------------------------- 5.2/48.9 MB 860.3 kB/s eta 0:00:51
   ---- ----------------------------------- 5.2/48.9 MB 860.3 kB/s eta 0:00:51
   ---- ----------------------------------- 5.5/48.9 MB 843.0 kB/s eta 0:00:52
   ---- ----------------------------------- 5.8/48.9 MB 851.1 kB/s eta 0:00:51
   ---- ----------------------------------- 5.8/48.9 MB 851.1 kB/s eta 0:00:51
   ---- ----------------------------------- 6.0/48.9 MB 858.7 kB/s eta 0:00:50
   ----- ---------------------------------- 6.3/48.9 MB 859.6 kB/s eta 0:00:50
   ----- ---------------------------------- 6.3/48.9 MB 859.6 kB/s eta 0:00:50
   ----- ---------------------------------- 6.6/48.9 MB 853.2 kB/s eta 0:00:50
   ----- ---------------------------------- 6.8/48.9 MB 857.3 kB/s eta 0:00:50
   ----- ---------------------------------- 7.1/48.9 MB 865.7 kB/s eta 0:00:49
   ----- ---------------------------------- 7.3/48.9 MB 876.1 kB/s eta 0:00:48
   ------ --------------------------------- 7.6/48.9 MB 879.6 kB/s eta 0:00:47
   ------ --------------------------------- 7.6/48.9 MB 879.6 kB/s eta 0:00:47
   ------ --------------------------------- 7.6/48.9 MB 879.6 kB/s eta 0:00:47
   ------ --------------------------------- 7.9/48.9 MB 858.9 kB/s eta 0:00:48
   ------ --------------------------------- 8.1/48.9 MB 857.9 kB/s eta 0:00:48
   ------ --------------------------------- 8.4/48.9 MB 863.4 kB/s eta 0:00:47
   ------- -------------------------------- 8.7/48.9 MB 874.6 kB/s eta 0:00:47
   ------- -------------------------------- 8.7/48.9 MB 874.6 kB/s eta 0:00:47
   ------- -------------------------------- 8.9/48.9 MB 874.4 kB/s eta 0:00:46
   ------- -------------------------------- 9.2/48.9 MB 872.1 kB/s eta 0:00:46
   ------- -------------------------------- 9.4/48.9 MB 879.8 kB/s eta 0:00:45
   ------- -------------------------------- 9.7/48.9 MB 885.8 kB/s eta 0:00:45
   ------- -------------------------------- 9.7/48.9 MB 885.8 kB/s eta 0:00:45
   -------- ------------------------------- 10.2/48.9 MB 898.0 kB/s eta 0:00:44
   -------- ------------------------------- 10.2/48.9 MB 898.0 kB/s eta 0:00:44
   -------- ------------------------------- 10.5/48.9 MB 894.1 kB/s eta 0:00:44
   -------- ------------------------------- 10.7/48.9 MB 897.7 kB/s eta 0:00:43
   -------- ------------------------------- 10.7/48.9 MB 897.7 kB/s eta 0:00:43
   -------- ------------------------------- 11.0/48.9 MB 893.4 kB/s eta 0:00:43
   -------- ------------------------------- 11.0/48.9 MB 893.4 kB/s eta 0:00:43
   --------- ------------------------------ 11.3/48.9 MB 888.7 kB/s eta 0:00:43
   --------- ------------------------------ 11.5/48.9 MB 891.0 kB/s eta 0:00:42
   --------- ------------------------------ 11.5/48.9 MB 891.0 kB/s eta 0:00:42
   --------- ------------------------------ 11.8/48.9 MB 886.5 kB/s eta 0:00:42
   --------- ------------------------------ 12.1/48.9 MB 879.8 kB/s eta 0:00:42
   --------- ------------------------------ 12.1/48.9 MB 879.8 kB/s eta 0:00:42
   ---------- ----------------------------- 12.3/48.9 MB 880.6 kB/s eta 0:00:42
   ---------- ----------------------------- 12.6/48.9 MB 883.4 kB/s eta 0:00:42
   ---------- ----------------------------- 12.8/48.9 MB 889.1 kB/s eta 0:00:41
   ---------- ----------------------------- 13.1/48.9 MB 895.3 kB/s eta 0:00:41
   ---------- ----------------------------- 13.4/48.9 MB 900.3 kB/s eta 0:00:40
   ----------- ---------------------------- 13.6/48.9 MB 902.7 kB/s eta 0:00:40
   ----------- ---------------------------- 13.6/48.9 MB 902.7 kB/s eta 0:00:40
   ----------- ---------------------------- 13.9/48.9 MB 899.4 kB/s eta 0:00:39
   ----------- ---------------------------- 14.2/48.9 MB 899.8 kB/s eta 0:00:39
   ----------- ---------------------------- 14.2/48.9 MB 899.8 kB/s eta 0:00:39
   ----------- ---------------------------- 14.4/48.9 MB 897.8 kB/s eta 0:00:39
   ----------- ---------------------------- 14.7/48.9 MB 900.3 kB/s eta 0:00:39
   ------------ --------------------------- 14.9/48.9 MB 900.3 kB/s eta 0:00:38
   ------------ --------------------------- 15.2/48.9 MB 900.6 kB/s eta 0:00:38
   ------------ --------------------------- 15.2/48.9 MB 900.6 kB/s eta 0:00:38
   ------------ --------------------------- 15.5/48.9 MB 900.5 kB/s eta 0:00:38
   ------------ --------------------------- 15.7/48.9 MB 902.2 kB/s eta 0:00:37
   ------------ --------------------------- 15.7/48.9 MB 902.2 kB/s eta 0:00:37
   ------------- -------------------------- 16.0/48.9 MB 899.5 kB/s eta 0:00:37
   ------------- -------------------------- 16.0/48.9 MB 899.5 kB/s eta 0:00:37
   ------------- -------------------------- 16.0/48.9 MB 899.5 kB/s eta 0:00:37
   ------------- -------------------------- 16.3/48.9 MB 882.7 kB/s eta 0:00:38
   ------------- -------------------------- 16.3/48.9 MB 882.7 kB/s eta 0:00:38
   ------------- -------------------------- 16.5/48.9 MB 875.6 kB/s eta 0:00:38
   ------------- -------------------------- 16.8/48.9 MB 877.7 kB/s eta 0:00:37
   ------------- -------------------------- 17.0/48.9 MB 881.7 kB/s eta 0:00:37
   ------------- -------------------------- 17.0/48.9 MB 881.7 kB/s eta 0:00:37
   -------------- ------------------------- 17.3/48.9 MB 877.0 kB/s eta 0:00:37
   -------------- ------------------------- 17.3/48.9 MB 877.0 kB/s eta 0:00:37
   -------------- ------------------------- 17.6/48.9 MB 873.2 kB/s eta 0:00:36
   -------------- ------------------------- 17.8/48.9 MB 872.2 kB/s eta 0:00:36
   -------------- ------------------------- 17.8/48.9 MB 872.2 kB/s eta 0:00:36
   -------------- ------------------------- 18.4/48.9 MB 879.7 kB/s eta 0:00:35
   --------------- ------------------------ 18.6/48.9 MB 884.8 kB/s eta 0:00:35
   --------------- ------------------------ 18.9/48.9 MB 889.3 kB/s eta 0:00:34
   --------------- ------------------------ 19.1/48.9 MB 890.1 kB/s eta 0:00:34
   --------------- ------------------------ 19.4/48.9 MB 894.7 kB/s eta 0:00:34
   --------------- ------------------------ 19.4/48.9 MB 894.7 kB/s eta 0:00:34
   ---------------- ----------------------- 19.7/48.9 MB 895.7 kB/s eta 0:00:33
   ---------------- ----------------------- 19.9/48.9 MB 899.2 kB/s eta 0:00:33
   ---------------- ----------------------- 20.2/48.9 MB 901.3 kB/s eta 0:00:32
   ---------------- ----------------------- 20.4/48.9 MB 903.2 kB/s eta 0:00:32
   ---------------- ----------------------- 20.7/48.9 MB 904.1 kB/s eta 0:00:32
   ---------------- ----------------------- 20.7/48.9 MB 904.1 kB/s eta 0:00:32
   ----------------- ---------------------- 21.0/48.9 MB 899.4 kB/s eta 0:00:32
   ----------------- ---------------------- 21.0/48.9 MB 899.4 kB/s eta 0:00:32
   ----------------- ---------------------- 21.0/48.9 MB 899.4 kB/s eta 0:00:32
   ----------------- ---------------------- 21.2/48.9 MB 889.4 kB/s eta 0:00:32
   ----------------- ---------------------- 21.5/48.9 MB 890.5 kB/s eta 0:00:31
   ----------------- ---------------------- 21.8/48.9 MB 894.6 kB/s eta 0:00:31
   ----------------- ---------------------- 22.0/48.9 MB 896.3 kB/s eta 0:00:31
   ------------------ --------------------- 22.3/48.9 MB 896.9 kB/s eta 0:00:30
   ------------------ --------------------- 22.3/48.9 MB 896.9 kB/s eta 0:00:30
   ------------------ --------------------- 22.5/48.9 MB 898.8 kB/s eta 0:00:30
   ------------------ --------------------- 22.8/48.9 MB 898.8 kB/s eta 0:00:30
   ------------------ --------------------- 23.1/48.9 MB 900.2 kB/s eta 0:00:29
   ------------------- -------------------- 23.3/48.9 MB 902.5 kB/s eta 0:00:29
   ------------------- -------------------- 23.3/48.9 MB 902.5 kB/s eta 0:00:29
   ------------------- -------------------- 23.6/48.9 MB 903.6 kB/s eta 0:00:29
   ------------------- -------------------- 23.9/48.9 MB 904.8 kB/s eta 0:00:28
   ------------------- -------------------- 24.1/48.9 MB 907.3 kB/s eta 0:00:28
   ------------------- -------------------- 24.4/48.9 MB 910.6 kB/s eta 0:00:27
   -------------------- ------------------- 24.9/48.9 MB 918.2 kB/s eta 0:00:27
   -------------------- ------------------- 25.2/48.9 MB 922.4 kB/s eta 0:00:26
   -------------------- ------------------- 25.2/48.9 MB 922.4 kB/s eta 0:00:26
   -------------------- ------------------- 25.4/48.9 MB 921.6 kB/s eta 0:00:26
   -------------------- ------------------- 25.7/48.9 MB 918.8 kB/s eta 0:00:26
   -------------------- ------------------- 25.7/48.9 MB 918.8 kB/s eta 0:00:26
   --------------------- ------------------ 26.0/48.9 MB 919.1 kB/s eta 0:00:26
   --------------------- ------------------ 26.2/48.9 MB 917.9 kB/s eta 0:00:25
   --------------------- ------------------ 26.5/48.9 MB 919.0 kB/s eta 0:00:25
   --------------------- ------------------ 26.7/48.9 MB 921.4 kB/s eta 0:00:25
   ---------------------- ----------------- 27.0/48.9 MB 924.2 kB/s eta 0:00:24
   ---------------------- ----------------- 27.0/48.9 MB 924.2 kB/s eta 0:00:24
   ---------------------- ----------------- 27.3/48.9 MB 923.9 kB/s eta 0:00:24
   ---------------------- ----------------- 27.5/48.9 MB 925.0 kB/s eta 0:00:24
   ---------------------- ----------------- 27.5/48.9 MB 925.0 kB/s eta 0:00:24
   ---------------------- ----------------- 27.8/48.9 MB 924.0 kB/s eta 0:00:23
   ---------------------- ----------------- 28.0/48.9 MB 923.8 kB/s eta 0:00:23
   ----------------------- ---------------- 28.3/48.9 MB 923.9 kB/s eta 0:00:23
   ----------------------- ---------------- 28.6/48.9 MB 924.1 kB/s eta 0:00:23
   ----------------------- ---------------- 29.1/48.9 MB 927.4 kB/s eta 0:00:22
   ----------------------- ---------------- 29.4/48.9 MB 930.2 kB/s eta 0:00:22
   ------------------------ --------------- 29.6/48.9 MB 935.9 kB/s eta 0:00:21
   ------------------------ --------------- 29.6/48.9 MB 935.9 kB/s eta 0:00:21
   ------------------------ --------------- 29.9/48.9 MB 937.0 kB/s eta 0:00:21
   ------------------------ --------------- 30.1/48.9 MB 942.8 kB/s eta 0:00:20
   ------------------------ --------------- 30.4/48.9 MB 945.6 kB/s eta 0:00:20
   ------------------------- -------------- 30.7/48.9 MB 945.8 kB/s eta 0:00:20
   ------------------------- -------------- 30.9/48.9 MB 950.7 kB/s eta 0:00:19
   ------------------------- -------------- 31.2/48.9 MB 954.1 kB/s eta 0:00:19
   ------------------------- -------------- 31.5/48.9 MB 965.9 kB/s eta 0:00:19
   ------------------------- -------------- 31.7/48.9 MB 966.5 kB/s eta 0:00:18
   -------------------------- ------------- 32.0/48.9 MB 968.7 kB/s eta 0:00:18
   -------------------------- ------------- 32.2/48.9 MB 972.4 kB/s eta 0:00:18
   -------------------------- ------------- 32.5/48.9 MB 973.7 kB/s eta 0:00:17
   -------------------------- ------------- 32.8/48.9 MB 972.4 kB/s eta 0:00:17
   -------------------------- ------------- 33.0/48.9 MB 973.5 kB/s eta 0:00:17
   --------------------------- ------------ 33.3/48.9 MB 972.9 kB/s eta 0:00:17
   --------------------------- ------------ 33.6/48.9 MB 971.2 kB/s eta 0:00:16
   --------------------------- ------------ 33.8/48.9 MB 977.2 kB/s eta 0:00:16
   --------------------------- ------------ 33.8/48.9 MB 977.2 kB/s eta 0:00:16
   --------------------------- ------------ 34.1/48.9 MB 981.7 kB/s eta 0:00:16
   ---------------------------- ----------- 34.3/48.9 MB 979.6 kB/s eta 0:00:15
   ---------------------------- ----------- 34.6/48.9 MB 984.7 kB/s eta 0:00:15
   ---------------------------- ----------- 34.9/48.9 MB 988.3 kB/s eta 0:00:15
   ---------------------------- ----------- 35.1/48.9 MB 997.5 kB/s eta 0:00:14
   ---------------------------- ----------- 35.4/48.9 MB 998.0 kB/s eta 0:00:14
   ----------------------------- ---------- 35.7/48.9 MB 998.5 kB/s eta 0:00:14
   ----------------------------- ---------- 35.9/48.9 MB 1.0 MB/s eta 0:00:14
   ----------------------------- ---------- 36.2/48.9 MB 1.0 MB/s eta 0:00:13
   ----------------------------- ---------- 36.2/48.9 MB 1.0 MB/s eta 0:00:13
   ----------------------------- ---------- 36.4/48.9 MB 1.0 MB/s eta 0:00:13
   ----------------------------- ---------- 36.7/48.9 MB 1.0 MB/s eta 0:00:13
   ----------------------------- ---------- 36.7/48.9 MB 1.0 MB/s eta 0:00:13
   ------------------------------ --------- 37.0/48.9 MB 997.7 kB/s eta 0:00:13
   ------------------------------ --------- 37.2/48.9 MB 994.4 kB/s eta 0:00:12
   ------------------------------ --------- 37.5/48.9 MB 1.0 MB/s eta 0:00:12
   ------------------------------ --------- 37.5/48.9 MB 1.0 MB/s eta 0:00:12
   ------------------------------ --------- 37.7/48.9 MB 1.0 MB/s eta 0:00:12
   ------------------------------- -------- 38.0/48.9 MB 1.0 MB/s eta 0:00:11
   ------------------------------- -------- 38.0/48.9 MB 1.0 MB/s eta 0:00:11
   ------------------------------- -------- 38.0/48.9 MB 1.0 MB/s eta 0:00:11
   ------------------------------- -------- 38.3/48.9 MB 991.3 kB/s eta 0:00:11
   ------------------------------- -------- 38.3/48.9 MB 991.3 kB/s eta 0:00:11
   ------------------------------- -------- 38.5/48.9 MB 987.6 kB/s eta 0:00:11
   ------------------------------- -------- 38.8/48.9 MB 985.4 kB/s eta 0:00:11
   ------------------------------- -------- 39.1/48.9 MB 987.9 kB/s eta 0:00:11
   -------------------------------- ------- 39.3/48.9 MB 989.1 kB/s eta 0:00:10
   -------------------------------- ------- 39.6/48.9 MB 988.8 kB/s eta 0:00:10
   -------------------------------- ------- 39.8/48.9 MB 989.0 kB/s eta 0:00:10
   -------------------------------- ------- 39.8/48.9 MB 989.0 kB/s eta 0:00:10
   -------------------------------- ------- 40.1/48.9 MB 989.4 kB/s eta 0:00:09
   -------------------------------- ------- 40.4/48.9 MB 987.4 kB/s eta 0:00:09
   --------------------------------- ------ 40.6/48.9 MB 992.5 kB/s eta 0:00:09
   --------------------------------- ------ 40.9/48.9 MB 997.2 kB/s eta 0:00:09
   --------------------------------- ------ 40.9/48.9 MB 997.2 kB/s eta 0:00:09
   --------------------------------- ------ 41.2/48.9 MB 995.1 kB/s eta 0:00:08
   --------------------------------- ------ 41.2/48.9 MB 995.1 kB/s eta 0:00:08
   --------------------------------- ------ 41.4/48.9 MB 994.7 kB/s eta 0:00:08
   ---------------------------------- ----- 41.7/48.9 MB 999.9 kB/s eta 0:00:08
   ---------------------------------- ----- 41.9/48.9 MB 998.5 kB/s eta 0:00:08
   ---------------------------------- ----- 42.2/48.9 MB 1.0 MB/s eta 0:00:07
   ---------------------------------- ----- 42.5/48.9 MB 1.0 MB/s eta 0:00:07
   ---------------------------------- ----- 42.7/48.9 MB 1.0 MB/s eta 0:00:07
   ---------------------------------- ----- 42.7/48.9 MB 1.0 MB/s eta 0:00:07
   ----------------------------------- ---- 43.0/48.9 MB 997.5 kB/s eta 0:00:06
   ----------------------------------- ---- 43.3/48.9 MB 996.8 kB/s eta 0:00:06
   ----------------------------------- ---- 43.5/48.9 MB 998.9 kB/s eta 0:00:06
   ----------------------------------- ---- 43.5/48.9 MB 998.9 kB/s eta 0:00:06
   ----------------------------------- ---- 43.8/48.9 MB 999.3 kB/s eta 0:00:06
   ----------------------------------- ---- 44.0/48.9 MB 997.9 kB/s eta 0:00:05
   ------------------------------------ --- 44.3/48.9 MB 999.5 kB/s eta 0:00:05
   ------------------------------------ --- 44.6/48.9 MB 1.0 MB/s eta 0:00:05
   ------------------------------------ --- 44.8/48.9 MB 1.0 MB/s eta 0:00:05
   ------------------------------------ --- 45.1/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.4/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.6/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.6/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.9/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.9/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 45.9/48.9 MB 1.0 MB/s eta 0:00:04
   ------------------------------------- -- 46.1/48.9 MB 1.0 MB/s eta 0:00:03
   ------------------------------------- -- 46.1/48.9 MB 1.0 MB/s eta 0:00:03
   ------------------------------------- -- 46.4/48.9 MB 1.0 MB/s eta 0:00:03
   -------------------------------------- - 46.9/48.9 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 47.2/48.9 MB 1.0 MB/s eta 0:00:02
   -------------------------------------- - 47.7/48.9 MB 1.0 MB/s eta 0:00:02
   ---------------------------------------  48.0/48.9 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------  48.2/48.9 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------  48.5/48.9 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------  48.8/48.9 MB 1.1 MB/s eta 0:00:01
   ---------------------------------------- 48.9/48.9 MB 1.0 MB/s  0:00:50
Installing collected packages: xgboost
Successfully installed xgboost-3.4.1
Note: you may need to restart the kernel to use updated packages.

XGBoost

In [14]:
from xgboost import XGBClassifier

In [15]:
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = XGBClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n)
            gbm.fit(ct_ohe_tr, y_train)
            pred = gbm.predict(ct_ohe_tst)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [00:19<00:00,  1.93s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.504444        NaN           100         0.988220
1        0.306667        NaN           100         0.987997
2        0.603333        NaN            50         0.987775
3        0.702222        NaN            50         0.987775
4        0.702222        NaN           100         0.987553
5        0.900000        NaN            50         0.987553
6        0.405556        NaN           100         0.987331
7        0.603333        NaN           100         0.987108
8        0.504444        NaN            50         0.987108
9        0.801111        NaN            50         0.987108
10       0.900000        NaN           100         0.987108
11       0.405556        NaN            50         0.985775
12       0.801111        NaN            25         0.985775
13       0.801111        NaN           100         0.985775
14       0.702222        4.0           100         0.985552
15       0.702222        NaN            25         0.985108
16       0.900000        4.0           100         0.984886
17       0.306667        NaN            50         0.984663
18       0.207778        NaN           100         0.984441
19       0.801111        4.0           100         0.984441

Light GBM

In [1]:
pip install lightgbm

Collecting lightgbm
  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl.metadata (18 kB)
Requirement already satisfied: narwhals>=1.15 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from lightgbm) (2.23.0)
Requirement already satisfied: numpy>=1.21.3 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from lightgbm) (2.4.6)
Requirement already satisfied: scipy in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from lightgbm) (1.18.0)
Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
   ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
   --------------- ------------------------ 0.5/1.4 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 1.0/1.4 MB 3.4 MB/s eta 0:00:01
   ---------------------------------------- 1.4/1.4 MB 2.7 MB/s  0:00:00
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0
Note: you may need to restart the kernel to use updated packages.

In [16]:
from lightgbm import LGBMClassifier

In [17]:
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = LGBMClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n, verbose = -1)
            gbm.fit(ct_ohe_tr, y_train)
            pred = gbm.predict(ct_ohe_tst)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [00:09<00:00,  1.07it/s]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.306667        NaN            50         0.988664
1        0.207778        NaN           100         0.988664
2        0.405556        NaN           100         0.988442
3        0.306667        NaN           100         0.988442
4        0.504444        NaN            50         0.988442
5        0.405556        NaN            50         0.987997
6        0.504444        NaN           100         0.987775
7        0.603333        NaN           100         0.987108
8        0.207778        NaN            50         0.986664
9        0.405556        NaN            25         0.986664
10       0.108889        NaN           100         0.986441
11       0.603333        NaN            50         0.986219
12       0.504444        NaN            25         0.985997
13       0.504444        4.0           100         0.984886
14       0.306667        NaN            25         0.984219
15       0.702222        4.0           100         0.984219
16       0.405556        4.0           100         0.983552
17       0.603333        4.0           100         0.983107
18       0.306667        4.0           100         0.981996
19       0.108889        NaN            50         0.981551

Catboost

In [18]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (3.11.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (2.4.6)
Requirement already satisfied: pandas<4.0,>=0.24 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (3.0.3)
Requirement already satisfied: scipy in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (1.18.0)
Requirement already satisfied: plotly in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (1.4.9)
Requirement already satisfied: packaging>=20.0 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (26.0)
Requirement already satisfied: pillow>=9 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from matplotlib->catboost) (3.2.5)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages (from plotly->catboost) (2.23.0)
Downloading catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 2.3 MB/s eta 0:00:45
   ---------------------------------------- 0.5/101.7 MB 2.3 MB/s eta 0:00:45
   ---------------------------------------- 0.8/101.7 MB 1.5 MB/s eta 0:01:10
   ---------------------------------------- 0.8/101.7 MB 1.5 MB/s eta 0:01:10
   ---------------------------------------- 0.8/101.7 MB 1.5 MB/s eta 0:01:10
   ---------------------------------------- 1.0/101.7 MB 797.6 kB/s eta 0:02:07
   ---------------------------------------- 1.0/101.7 MB 797.6 kB/s eta 0:02:07
    --------------------------------------- 1.3/101.7 MB 686.6 kB/s eta 0:02:27
    --------------------------------------- 1.3/101.7 MB 686.6 kB/s eta 0:02:27
    --------------------------------------- 1.3/101.7 MB 686.6 kB/s eta 0:02:27
    --------------------------------------- 1.6/101.7 MB 633.4 kB/s eta 0:02:39
    --------------------------------------- 1.6/101.7 MB 633.4 kB/s eta 0:02:39
    --------------------------------------- 1.6/101.7 MB 633.4 kB/s eta 0:02:39
    --------------------------------------- 1.8/101.7 MB 569.8 kB/s eta 0:02:56
    --------------------------------------- 1.8/101.7 MB 569.8 kB/s eta 0:02:56
    --------------------------------------- 1.8/101.7 MB 569.8 kB/s eta 0:02:56
    --------------------------------------- 2.1/101.7 MB 527.2 kB/s eta 0:03:10
    --------------------------------------- 2.1/101.7 MB 527.2 kB/s eta 0:03:10
    --------------------------------------- 2.1/101.7 MB 527.2 kB/s eta 0:03:10
    --------------------------------------- 2.1/101.7 MB 527.2 kB/s eta 0:03:10
    --------------------------------------- 2.4/101.7 MB 491.4 kB/s eta 0:03:23
    --------------------------------------- 2.4/101.7 MB 491.4 kB/s eta 0:03:23
   - -------------------------------------- 2.6/101.7 MB 499.8 kB/s eta 0:03:19
   - -------------------------------------- 2.6/101.7 MB 499.8 kB/s eta 0:03:19
   - -------------------------------------- 2.6/101.7 MB 499.8 kB/s eta 0:03:19
   - -------------------------------------- 2.6/101.7 MB 499.8 kB/s eta 0:03:19
   - -------------------------------------- 2.9/101.7 MB 468.3 kB/s eta 0:03:32
   - -------------------------------------- 2.9/101.7 MB 468.3 kB/s eta 0:03:32
   - -------------------------------------- 2.9/101.7 MB 468.3 kB/s eta 0:03:32
   - -------------------------------------- 3.1/101.7 MB 464.7 kB/s eta 0:03:33
   - -------------------------------------- 3.1/101.7 MB 464.7 kB/s eta 0:03:33
   - -------------------------------------- 3.1/101.7 MB 464.7 kB/s eta 0:03:33
   - -------------------------------------- 3.4/101.7 MB 464.1 kB/s eta 0:03:32
   - -------------------------------------- 3.4/101.7 MB 464.1 kB/s eta 0:03:32
   - -------------------------------------- 3.7/101.7 MB 478.6 kB/s eta 0:03:25
   - -------------------------------------- 3.7/101.7 MB 478.6 kB/s eta 0:03:25
   - -------------------------------------- 3.9/101.7 MB 481.6 kB/s eta 0:03:24
   - -------------------------------------- 3.9/101.7 MB 481.6 kB/s eta 0:03:24
   - -------------------------------------- 3.9/101.7 MB 481.6 kB/s eta 0:03:24
   - -------------------------------------- 3.9/101.7 MB 481.6 kB/s eta 0:03:24
   - -------------------------------------- 4.2/101.7 MB 467.2 kB/s eta 0:03:29
   - -------------------------------------- 4.2/101.7 MB 467.2 kB/s eta 0:03:29
   - -------------------------------------- 4.5/101.7 MB 479.5 kB/s eta 0:03:23
   - -------------------------------------- 4.7/101.7 MB 496.6 kB/s eta 0:03:16
   - -------------------------------------- 5.0/101.7 MB 511.8 kB/s eta 0:03:10
   - -------------------------------------- 5.0/101.7 MB 511.8 kB/s eta 0:03:10
   -- ------------------------------------- 5.2/101.7 MB 520.3 kB/s eta 0:03:06
   -- ------------------------------------- 5.2/101.7 MB 520.3 kB/s eta 0:03:06
   -- ------------------------------------- 5.2/101.7 MB 520.3 kB/s eta 0:03:06
   -- ------------------------------------- 5.2/101.7 MB 520.3 kB/s eta 0:03:06
   -- ------------------------------------- 5.5/101.7 MB 495.5 kB/s eta 0:03:15
   -- ------------------------------------- 5.5/101.7 MB 495.5 kB/s eta 0:03:15
   -- ------------------------------------- 5.5/101.7 MB 495.5 kB/s eta 0:03:15
   -- ------------------------------------- 5.5/101.7 MB 495.5 kB/s eta 0:03:15
   -- ------------------------------------- 5.8/101.7 MB 486.2 kB/s eta 0:03:18
   -- ------------------------------------- 5.8/101.7 MB 486.2 kB/s eta 0:03:18
   -- ------------------------------------- 5.8/101.7 MB 486.2 kB/s eta 0:03:18
   -- ------------------------------------- 5.8/101.7 MB 486.2 kB/s eta 0:03:18
   -- ------------------------------------- 6.0/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.0/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.0/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.3/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.3/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.3/101.7 MB 470.1 kB/s eta 0:03:24
   -- ------------------------------------- 6.6/101.7 MB 466.7 kB/s eta 0:03:24
   -- ------------------------------------- 6.6/101.7 MB 466.7 kB/s eta 0:03:24
   -- ------------------------------------- 6.6/101.7 MB 466.7 kB/s eta 0:03:24
   -- ------------------------------------- 6.8/101.7 MB 462.0 kB/s eta 0:03:26
   -- ------------------------------------- 6.8/101.7 MB 462.0 kB/s eta 0:03:26
   -- ------------------------------------- 7.1/101.7 MB 467.3 kB/s eta 0:03:23
   -- ------------------------------------- 7.1/101.7 MB 467.3 kB/s eta 0:03:23
   -- ------------------------------------- 7.3/101.7 MB 473.7 kB/s eta 0:03:20
   -- ------------------------------------- 7.3/101.7 MB 473.7 kB/s eta 0:03:20
   -- ------------------------------------- 7.3/101.7 MB 473.7 kB/s eta 0:03:20
   -- ------------------------------------- 7.6/101.7 MB 473.1 kB/s eta 0:03:19
   -- ------------------------------------- 7.6/101.7 MB 473.1 kB/s eta 0:03:19
   -- ------------------------------------- 7.6/101.7 MB 473.1 kB/s eta 0:03:19
   --- ------------------------------------ 7.9/101.7 MB 470.2 kB/s eta 0:03:20
   --- ------------------------------------ 7.9/101.7 MB 470.2 kB/s eta 0:03:20
   --- ------------------------------------ 8.1/101.7 MB 475.3 kB/s eta 0:03:17
   --- ------------------------------------ 8.1/101.7 MB 475.3 kB/s eta 0:03:17
   --- ------------------------------------ 8.4/101.7 MB 478.8 kB/s eta 0:03:15
   --- ------------------------------------ 8.4/101.7 MB 478.8 kB/s eta 0:03:15
   --- ------------------------------------ 8.4/101.7 MB 478.8 kB/s eta 0:03:15
   --- ------------------------------------ 8.7/101.7 MB 475.8 kB/s eta 0:03:16
   --- ------------------------------------ 8.7/101.7 MB 475.8 kB/s eta 0:03:16
   --- ------------------------------------ 8.7/101.7 MB 475.8 kB/s eta 0:03:16
   --- ------------------------------------ 8.9/101.7 MB 474.6 kB/s eta 0:03:16
   --- ------------------------------------ 9.2/101.7 MB 479.1 kB/s eta 0:03:14
   --- ------------------------------------ 9.2/101.7 MB 479.1 kB/s eta 0:03:14
   --- ------------------------------------ 9.2/101.7 MB 479.1 kB/s eta 0:03:14
   --- ------------------------------------ 9.2/101.7 MB 479.1 kB/s eta 0:03:14
   --- ------------------------------------ 9.4/101.7 MB 473.2 kB/s eta 0:03:16
   --- ------------------------------------ 9.4/101.7 MB 473.2 kB/s eta 0:03:16
   --- ------------------------------------ 9.7/101.7 MB 478.1 kB/s eta 0:03:13
   --- ------------------------------------ 9.7/101.7 MB 478.1 kB/s eta 0:03:13
   --- ----------------------------------- 10.0/101.7 MB 482.5 kB/s eta 0:03:11
   --- ----------------------------------- 10.2/101.7 MB 488.1 kB/s eta 0:03:08
   ---- ---------------------------------- 10.5/101.7 MB 495.6 kB/s eta 0:03:05
   ---- ---------------------------------- 10.5/101.7 MB 495.6 kB/s eta 0:03:05
   ---- ---------------------------------- 10.5/101.7 MB 495.6 kB/s eta 0:03:05
   ---- ---------------------------------- 10.7/101.7 MB 495.1 kB/s eta 0:03:04
   ---- ---------------------------------- 11.0/101.7 MB 499.6 kB/s eta 0:03:02
   ---- ---------------------------------- 11.0/101.7 MB 499.6 kB/s eta 0:03:02
   ---- ---------------------------------- 11.3/101.7 MB 503.6 kB/s eta 0:03:00
   ---- ---------------------------------- 11.3/101.7 MB 503.6 kB/s eta 0:03:00
   ---- ---------------------------------- 11.5/101.7 MB 504.3 kB/s eta 0:02:59
   ---- ---------------------------------- 11.5/101.7 MB 504.3 kB/s eta 0:02:59
   ---- ---------------------------------- 11.8/101.7 MB 506.9 kB/s eta 0:02:58
   ---- ---------------------------------- 11.8/101.7 MB 506.9 kB/s eta 0:02:58
   ---- ---------------------------------- 11.8/101.7 MB 506.9 kB/s eta 0:02:58
   ---- ---------------------------------- 12.1/101.7 MB 506.4 kB/s eta 0:02:58
   ---- ---------------------------------- 12.1/101.7 MB 506.4 kB/s eta 0:02:58
   ---- ---------------------------------- 12.1/101.7 MB 506.4 kB/s eta 0:02:58
   ---- ---------------------------------- 12.3/101.7 MB 502.3 kB/s eta 0:02:59
   ---- ---------------------------------- 12.3/101.7 MB 502.3 kB/s eta 0:02:59
   ---- ---------------------------------- 12.3/101.7 MB 502.3 kB/s eta 0:02:59
   ---- ---------------------------------- 12.6/101.7 MB 501.9 kB/s eta 0:02:58
   ---- ---------------------------------- 12.6/101.7 MB 501.9 kB/s eta 0:02:58
   ---- ---------------------------------- 12.6/101.7 MB 501.9 kB/s eta 0:02:58
   ---- ---------------------------------- 12.6/101.7 MB 501.9 kB/s eta 0:02:58
   ---- ---------------------------------- 12.8/101.7 MB 493.4 kB/s eta 0:03:01
   ---- ---------------------------------- 12.8/101.7 MB 493.4 kB/s eta 0:03:01
   ---- ---------------------------------- 12.8/101.7 MB 493.4 kB/s eta 0:03:01
   ----- --------------------------------- 13.1/101.7 MB 492.7 kB/s eta 0:03:00
   ----- --------------------------------- 13.1/101.7 MB 492.7 kB/s eta 0:03:00
   ----- --------------------------------- 13.1/101.7 MB 492.7 kB/s eta 0:03:00
   ----- --------------------------------- 13.4/101.7 MB 489.3 kB/s eta 0:03:01
   ----- --------------------------------- 13.4/101.7 MB 489.3 kB/s eta 0:03:01
   ----- --------------------------------- 13.4/101.7 MB 489.3 kB/s eta 0:03:01
   ----- --------------------------------- 13.4/101.7 MB 489.3 kB/s eta 0:03:01
   ----- --------------------------------- 13.4/101.7 MB 489.3 kB/s eta 0:03:01
   ----- --------------------------------- 13.6/101.7 MB 482.3 kB/s eta 0:03:03
   ----- --------------------------------- 13.6/101.7 MB 482.3 kB/s eta 0:03:03
   ----- --------------------------------- 13.9/101.7 MB 483.5 kB/s eta 0:03:02
   ----- --------------------------------- 13.9/101.7 MB 483.5 kB/s eta 0:03:02
   ----- --------------------------------- 13.9/101.7 MB 483.5 kB/s eta 0:03:02
   ----- --------------------------------- 14.2/101.7 MB 482.8 kB/s eta 0:03:02
   ----- --------------------------------- 14.4/101.7 MB 485.9 kB/s eta 0:03:00
   ----- --------------------------------- 14.4/101.7 MB 485.9 kB/s eta 0:03:00
   ----- --------------------------------- 14.4/101.7 MB 485.9 kB/s eta 0:03:00
   ----- --------------------------------- 14.4/101.7 MB 485.9 kB/s eta 0:03:00
   ----- --------------------------------- 14.7/101.7 MB 473.2 kB/s eta 0:03:04
   ----- --------------------------------- 14.7/101.7 MB 473.2 kB/s eta 0:03:04
   ----- --------------------------------- 14.7/101.7 MB 473.2 kB/s eta 0:03:04
   ----- --------------------------------- 14.9/101.7 MB 469.5 kB/s eta 0:03:05
   ----- --------------------------------- 14.9/101.7 MB 469.5 kB/s eta 0:03:05
   ----- --------------------------------- 15.2/101.7 MB 471.3 kB/s eta 0:03:04
   ----- --------------------------------- 15.2/101.7 MB 471.3 kB/s eta 0:03:04
   ----- --------------------------------- 15.2/101.7 MB 471.3 kB/s eta 0:03:04
   ----- --------------------------------- 15.5/101.7 MB 472.2 kB/s eta 0:03:03
   ----- --------------------------------- 15.5/101.7 MB 472.2 kB/s eta 0:03:03
   ------ -------------------------------- 15.7/101.7 MB 472.6 kB/s eta 0:03:03
   ------ -------------------------------- 15.7/101.7 MB 472.6 kB/s eta 0:03:03
   ------ -------------------------------- 15.7/101.7 MB 472.6 kB/s eta 0:03:03
   ------ -------------------------------- 15.7/101.7 MB 472.6 kB/s eta 0:03:03
   ------ -------------------------------- 16.0/101.7 MB 473.0 kB/s eta 0:03:02
   ------ -------------------------------- 16.0/101.7 MB 473.0 kB/s eta 0:03:02
   ------ -------------------------------- 16.0/101.7 MB 473.0 kB/s eta 0:03:02
   ------ -------------------------------- 16.3/101.7 MB 471.9 kB/s eta 0:03:02
   ------ -------------------------------- 16.5/101.7 MB 480.3 kB/s eta 0:02:58
   ------ -------------------------------- 16.5/101.7 MB 480.3 kB/s eta 0:02:58
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 16.8/101.7 MB 484.2 kB/s eta 0:02:56
   ------ -------------------------------- 17.0/101.7 MB 471.9 kB/s eta 0:03:00
   ------ -------------------------------- 17.0/101.7 MB 471.9 kB/s eta 0:03:00
   ------ -------------------------------- 17.0/101.7 MB 471.9 kB/s eta 0:03:00
   ------ -------------------------------- 17.0/101.7 MB 471.9 kB/s eta 0:03:00
   ------ -------------------------------- 17.0/101.7 MB 471.9 kB/s eta 0:03:00
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.3/101.7 MB 464.6 kB/s eta 0:03:02
   ------ -------------------------------- 17.6/101.7 MB 447.2 kB/s eta 0:03:09
   ------ -------------------------------- 17.6/101.7 MB 447.2 kB/s eta 0:03:09
   ------ -------------------------------- 17.6/101.7 MB 447.2 kB/s eta 0:03:09
   ------ -------------------------------- 17.6/101.7 MB 447.2 kB/s eta 0:03:09
   ------ -------------------------------- 17.8/101.7 MB 430.5 kB/s eta 0:03:15
   ------ -------------------------------- 17.8/101.7 MB 430.5 kB/s eta 0:03:15
   ------ -------------------------------- 17.8/101.7 MB 430.5 kB/s eta 0:03:15
   ------ -------------------------------- 18.1/101.7 MB 430.3 kB/s eta 0:03:15
   ------ -------------------------------- 18.1/101.7 MB 430.3 kB/s eta 0:03:15
   ------ -------------------------------- 18.1/101.7 MB 430.3 kB/s eta 0:03:15
   ------ -------------------------------- 18.1/101.7 MB 430.3 kB/s eta 0:03:15
   ------ -------------------------------- 18.1/101.7 MB 430.3 kB/s eta 0:03:15
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.4/101.7 MB 427.4 kB/s eta 0:03:16
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.6/101.7 MB 412.4 kB/s eta 0:03:22
   ------- ------------------------------- 18.9/101.7 MB 397.8 kB/s eta 0:03:29
   ------- ------------------------------- 18.9/101.7 MB 397.8 kB/s eta 0:03:29
   ------- ------------------------------- 18.9/101.7 MB 397.8 kB/s eta 0:03:29
   ------- ------------------------------- 19.1/101.7 MB 394.6 kB/s eta 0:03:30
   ------- ------------------------------- 19.1/101.7 MB 394.6 kB/s eta 0:03:30

In [19]:
from catboost import CatBoostClassifier

In [20]:
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []
for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = CatBoostClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n, verbose = False)
            gbm.fit(ct_ohe_tr, y_train)
            pred = gbm.predict(ct_ohe_tst)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [00:23<00:00,  2.30s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.801111        NaN           100         0.981551
1        0.900000        NaN           100         0.980440
2        0.702222        NaN           100         0.979773
3        0.900000        4.0           100         0.979106
4        0.603333        NaN           100         0.978884
5        0.702222        4.0           100         0.978662
6        0.603333        4.0           100         0.978440
7        0.504444        NaN           100         0.978440
8        0.801111        4.0           100         0.978440
9        0.306667        NaN           100         0.978217
10       0.900000        NaN            50         0.977773
11       0.603333        4.0            50         0.977551
12       0.801111        NaN            50         0.977328
13       0.405556        NaN           100         0.977328
14       0.702222        NaN            50         0.977106
15       0.405556        4.0           100         0.976884
16       0.207778        4.0           100         0.976884
17       0.603333        NaN            50         0.976661
18       0.504444        4.0           100         0.976661
19       0.207778        NaN           100         0.976439

In [22]:
categories = ['Department', 'salary']
learn_r = np.linspace(0.01, 0.9, 10)
max_depth = [None, 2,3,4]
n_est = [25,50,100]
scores = []

for r in tqdm(learn_r):
    for m in max_depth:
        for n in n_est:
            gbm = CatBoostClassifier(random_state=26, learning_rate=r, max_depth= m, n_estimators=n, cat_features= categories ,verbose = False)
            gbm.fit(X_train, y_train)
            pred = gbm.predict(X_test)
            scores.append([r,m,n, accuracy_score(y_test, pred)])
score_df=pd.DataFrame(scores,columns=["learning_rate",'max_depth','n_estimators','accuracy_score(' ])
score_df.sort_values(by="accuracy_score(",ascending=False,ignore_index=True)[:20]

100%|██████████| 10/10 [02:17<00:00, 13.70s/it]

    learning_rate  max_depth  n_estimators  accuracy_score(
0        0.900000        NaN           100         0.980885
1        0.801111        NaN           100         0.979773
2        0.702222        NaN           100         0.978662
3        0.801111        NaN            50         0.978440
4        0.801111        4.0           100         0.978217
5        0.702222        NaN            50         0.977106
6        0.801111        4.0            50         0.976661
7        0.405556        NaN           100         0.976439
8        0.504444        NaN           100         0.976439
9        0.405556        NaN            50         0.976439
10       0.900000        NaN            50         0.976439
11       0.801111        3.0           100         0.976217
12       0.504444        4.0           100         0.976217
13       0.504444        3.0           100         0.976217
14       0.603333        NaN           100         0.976217
15       0.801111        3.0            25         0.975995
16       0.603333        4.0            50         0.975995
17       0.603333        4.0           100         0.975995
18       0.207778        4.0           100         0.975995
19       0.207778        NaN           100         0.975995