In [3]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pandas as pd

In [5]:
df=pd.read_csv("F:\MACHINE LEARNING\SOMETHING\Datasets\Faceplate.csv")
df = df.astype(bool)
ap = apriori(df, min_support= 0.2,  use_colnames=True)
ap

    support                          itemsets
0       1.0                     (Transaction)
1       0.6                             (Red)
2       0.7                           (White)
3       0.6                            (Blue)
4       0.2                          (Orange)
5       0.2                           (Green)
6       0.6                (Transaction, Red)
7       0.7              (White, Transaction)
8       0.6               (Transaction, Blue)
9       0.2             (Transaction, Orange)
10      0.2              (Transaction, Green)
11      0.4                      (White, Red)
12      0.4                       (Red, Blue)
13      0.2                      (Red, Green)
14      0.4                     (White, Blue)
15      0.2                   (White, Orange)
16      0.2                    (White, Green)
17      0.4         (White, Transaction, Red)
18      0.4          (Transaction, Blue, Red)
19      0.2         (Transaction, Green, Red)
20      0.4        (White, Transaction, Blue)
21      0.2      (White, Transaction, Orange)
22      0.2       (White, Transaction, Green)
23      0.2                (White, Red, Blue)
24      0.2               (White, Red, Green)
25      0.2   (White, Transaction, Blue, Red)
26      0.2  (White, Transaction, Green, Red)

In [8]:
rules = association_rules(ap, metric = 'confidence', min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by = ['confidence','lift','support'], ascending = False)

C:\Users\PGCP-AI.STUDENTSDC\AppData\Local\anaconda3\Lib\site-packages\mlxtend\frequent_patterns\association_rules.py:184: RuntimeWarning: invalid value encountered in divide
  cert_metric = np.where(certainty_denom == 0, 0, certainty_num / certainty_denom)

,antecedents,consequents,support,confidence,lift
47,(Green),"(White, Red)",0.2,1.0,2.500000
62,"(Transaction, Green)","(White, Red)",0.2,1.0,2.500000
63,(Green),"(White, Red, Transaction)",0.2,1.0,2.500000
12,(Green),(Red),0.2,1.0,1.666667
27,"(Transaction, Green)",(Red),0.2,1.0,1.666667
...,...,...,...,...,...
52,"(White, Blue)","(Red, Transaction)",0.2,0.5,0.833333
53,"(White, Red)","(Transaction, Blue)",0.2,0.5,0.833333
43,"(Red, Blue)",(White),0.2,0.5,0.714286
51,"(Red, Blue, Transaction)",(White),0.2,0.5,0.714286
54,"(Red, Blue)","(White, Transaction)",0.2,0.5,0.714286

In [9]:
relv_rule = rules[rules['lift']>1]
relv_rule.sort_values(by =['confidence','lift','support'], ascending = False)

,antecedents,consequents,support,confidence,lift
47,(Green),"(White, Red)",0.2,1.000000,2.500000
62,"(Transaction, Green)","(White, Red)",0.2,1.000000,2.500000
63,(Green),"(White, Red, Transaction)",0.2,1.000000,2.500000
12,(Green),(Red),0.2,1.000000,1.666667
27,"(Transaction, Green)",(Red),0.2,1.000000,1.666667
29,(Green),"(Transaction, Red)",0.2,1.000000,1.666667
44,"(White, Green)",(Red),0.2,1.000000,1.666667
56,"(White, Green, Transaction)",(Red),0.2,1.000000,1.666667
59,"(White, Green)","(Red, Transaction)",0.2,1.000000,1.666667
15,(Orange),(White),0.2,1.000000,1.428571
16,(Green),(White),0.2,1.000000,1.428571
36,"(Transaction, Orange)",(White),0.2,1.000000,1.428571
37,(Orange),"(White, Transaction)",0.2,1.000000,1.428571
39,"(Transaction, Green)",(White),0.2,1.000000,1.428571
40,(Green),"(White, Transaction)",0.2,1.000000,1.428571
46,"(Red, Green)",(White),0.2,1.000000,1.428571
58,"(Red, Green, Transaction)",(White),0.2,1.000000,1.428571
61,"(Red, Green)","(White, Transaction)",0.2,1.000000,1.428571
10,(Red),(Blue),0.4,0.666667,1.111111
11,(Blue),(Red),0.4,0.666667,1.111111
22,"(Transaction, Blue)",(Red),0.4,0.666667,1.111111
23,"(Transaction, Red)",(Blue),0.4,0.666667,1.111111
25,(Blue),"(Transaction, Red)",0.4,0.666667,1.111111
26,(Red),"(Transaction, Blue)",0.4,0.666667,1.111111
45,"(White, Red)",(Green),0.2,0.500000,2.500000
57,"(White, Red, Transaction)",(Green),0.2,0.500000,2.500000
60,"(White, Red)","(Transaction, Green)",0.2,0.500000,2.500000

In [12]:
cosmetic = pd.read_csv("F:\MACHINE LEARNING\SOMETHING\Datasets\Cosmetics.csv", index_col=0)
cosmetic.head()

,Bag,Blush,Nail Polish,Brushes,Concealer,Eyebrow Pencils,Bronzer,Lip liner,Mascara,Eye shadow,Foundation,Lip Gloss,Lipstick,Eyeliner
Trans.,,,,,,,,,,,,,,
1,0,1,1,1,1,0,1,1,1,0,0,0,0,1
2,0,0,1,0,1,0,1,1,0,0,1,1,0,0
3,0,1,0,0,1,1,1,1,1,1,1,1,1,0
4,0,0,1,1,1,0,1,0,0,0,1,0,0,1
5,0,1,0,0,1,0,1,1,1,1,0,1,1,0

In [11]:
cos = cosmetic.astype(bool)
ap_cos = apriori(cos, min_support= 0.2,  use_colnames=True)
ap_cos

    support                  itemsets
0     0.363                   (Blush)
1     0.280             (Nail Polish)
2     0.442               (Concealer)
3     0.279                 (Bronzer)
4     0.234               (Lip liner)
5     0.357                 (Mascara)
6     0.381              (Eye shadow)
7     0.536              (Foundation)
8     0.490               (Lip Gloss)
9     0.322                (Lipstick)
10    0.457                (Eyeliner)
11    0.220        (Concealer, Blush)
12    0.204      (Mascara, Concealer)
13    0.201   (Concealer, Eye shadow)
14    0.231   (Concealer, Foundation)
15    0.218    (Concealer, Lip Gloss)
16    0.297     (Eyeliner, Concealer)
17    0.321     (Mascara, Eye shadow)
18    0.211  (Foundation, Eye shadow)
19    0.201   (Lip Gloss, Eye shadow)
20    0.356   (Lip Gloss, Foundation)
21    0.238    (Eyeliner, Foundation)
22    0.227     (Eyeliner, Lip Gloss)

In [13]:
rules = association_rules(ap_cos, metric = 'confidence', min_threshold=0.5)
rules = rules[['antecedents','consequents','support','confidence','lift']]
rules.sort_values(by = ['confidence','lift','support'], ascending = False)

     antecedents   consequents  support  confidence      lift
6      (Mascara)  (Eye shadow)    0.321    0.899160  2.359999
7   (Eye shadow)     (Mascara)    0.321    0.842520  2.359999
11   (Lip Gloss)  (Foundation)    0.356    0.726531  1.355468
5    (Concealer)    (Eyeliner)    0.297    0.671946  1.470341
10  (Foundation)   (Lip Gloss)    0.356    0.664179  1.355468
4     (Eyeliner)   (Concealer)    0.297    0.649891  1.470341
0        (Blush)   (Concealer)    0.220    0.606061  1.371178
1      (Mascara)   (Concealer)    0.204    0.571429  1.292825
8   (Eye shadow)  (Foundation)    0.211    0.553806  1.033220
2   (Eye shadow)   (Concealer)    0.201    0.527559  1.193573
9   (Eye shadow)   (Lip Gloss)    0.201    0.527559  1.076651
3    (Concealer)  (Foundation)    0.231    0.522624  0.975046
12    (Eyeliner)  (Foundation)    0.238    0.520788  0.971619

In [16]:
from ipywidgets import interact
import ipywidgets as widgets

In [19]:
def gen_rules(min_support, min_confidence):
    itemsets = apriori(cos, min_support= min_support, use_colnames = True)
    rules = association_rules(itemsets, metric = 'confidence', min_threshold= min_confidence)
    rules = rules[['antecedents','consequents','support','confidence','lift']]
    relv_rules = rules[rules['lift'] > 1]
    return relv_rules.sort_values(by = ['confidence', 'lift', 'support'], ascending = False)

In [20]:
interact(gen_rules,
         min_support = widgets.FloatSlider( value = 0.01, min = 0, max = 1, step = 0.01, description = 'Min Support: '),
         min_confidence = widgets.FloatSlider( value = 0.01, min =0, max = 1, step = 0.01, description = 'Min confidence'))

interactive(children=(FloatSlider(value=0.01, description='Min Support: ', max=1.0, step=0.01), FloatSlider(va…