In [10]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm
from sklearn.metrics import accuracy_score,r2_score
from sklearn.ensemble import BaggingClassifier,BaggingRegressor

In [2]:
df=pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Wisconsin\BreastCancer.csv",index_col=0)
X,y=df.drop('Class',axis=1),df['Class']
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=26,test_size=.3,stratify=y)
df.head()

        Clump  UniCell_Size  Uni_CellShape  MargAdh  SEpith  BareN  BChromatin  NoemN  Mitoses      Class
Code
61634       5             4              3        1       2      2           2      3        1     Benign
63375       9             1              2        6       4     10           7      7        2  Malignant
76389      10             4              7        2       2      8           6      1        1  Malignant
95719       6            10             10       10       8     10           7     10        7  Malignant
128059      1             1              1        1       2      5           5      1        1     Benign

In [4]:
lr=LogisticRegression()
knn=KNeighborsClassifier()
dtc=DecisionTreeClassifier(random_state=26)
bag=BaggingClassifier(estimator=lr,n_estimators=15,random_state=26)
bag.fit(X_train,y_train)
pred=bag.predict(X_test)
accuracy_score(y_test,pred)

0.9571428571428572

In [5]:
est = [lr,knn, dtc]
n_samples = [10,25,50]
scores = []
for e in est:
    for n in n_samples:
        bag = BaggingClassifier(estimator = e, n_estimators = n, random_state=26)
        bag.fit(X_train, y_train)
        pred = bag.predict(X_test)
        scores.append([e, n, accuracy_score(y_test, pred)])
df_scores = pd.DataFrame(scores, columns=['Estimator','n_estimator','Score'])
df_scores.sort_values('Score', ascending = False)

                                 Estimator  n_estimator     Score
6  DecisionTreeClassifier(random_state=26)           10  0.966667
5                   KNeighborsClassifier()           50  0.966667
7  DecisionTreeClassifier(random_state=26)           25  0.966667
3                   KNeighborsClassifier()           10  0.961905
2                     LogisticRegression()           50  0.961905
8  DecisionTreeClassifier(random_state=26)           50  0.961905
4                   KNeighborsClassifier()           25  0.961905
1                     LogisticRegression()           25  0.957143
0                     LogisticRegression()           10  0.952381

In [8]:
from sklearn.linear_model import Ridge,Lasso,LinearRegression
from sklearn.tree import DecisionTreeRegressor
concrete = pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Concrete_Strength\Concrete_Data.csv")
X,y=concrete.drop('Strength',axis=1),concrete.Strength
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.3,random_state=26)

In [12]:
ridge=Ridge()
lasso=Lasso()
lr=LinearRegression()
dtr=DecisionTreeRegressor(random_state=26)
est=[ridge,lasso,lr,dtr]
n_sample=[10,15,20,25,40,50]
scores=[]
for e in est:
    for n in n_sample:
        bag=BaggingRegressor(estimator=e,n_estimators=n,random_state=26)
        bag.fit(X_train,y_train)
        pred=bag.predict(X_test)
        scores.append([e,n,r2_score(y_test,pred)])
pd.DataFrame(scores,columns=["Estimator","n_estimator","score"]).sort_values("score",ascending=False,ignore_index=True)

                                 Estimator  n_estimator     score
0   DecisionTreeRegressor(random_state=26)           20  0.896735
1   DecisionTreeRegressor(random_state=26)           50  0.896730
2   DecisionTreeRegressor(random_state=26)           40  0.894846
3   DecisionTreeRegressor(random_state=26)           25  0.893895
4   DecisionTreeRegressor(random_state=26)           10  0.893069
5   DecisionTreeRegressor(random_state=26)           15  0.891974
6                                  Lasso()           10  0.620327
7                                  Ridge()           10  0.619630
8                       LinearRegression()           10  0.619629
9                                  Lasso()           15  0.619514
10                                 Ridge()           15  0.618851
11                      LinearRegression()           15  0.618851
12                                 Lasso()           50  0.618218
13                                 Lasso()           40  0.618166
14                                 Ridge()           40  0.617508
15                      LinearRegression()           40  0.617508
16                                 Ridge()           50  0.617487
17                      LinearRegression()           50  0.617486
18                                 Lasso()           20  0.616531
19                                 Lasso()           25  0.616078
20                                 Ridge()           20  0.615677
21                      LinearRegression()           20  0.615676
22                                 Ridge()           25  0.615382
23                      LinearRegression()           25  0.615382