In [2]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.metrics import accuracy_score
from sklearn.compose import make_column_selector,make_column_transformer
from sklearn.pipeline import Pipeline
import numpy as np
from tqdm import tqdm
import warnings
warnings.filterwarnings('ignore')

In [3]:
vehicle = pd.read_csv("F:\MACHINE LEARNING\SessionsMaterial\Cases\Vehicle Silhouettes\Vehicle.csv")
vehicle.head()

,Comp,Circ,D.Circ,Rad.Ra,Pr.Axis.Ra,Max.L.Ra,Scat.Ra,Elong,Pr.Axis.Rect,Max.L.Rect,Sc.Var.Maxis,Sc.Var.maxis,Ra.Gyr,Skew.Maxis,Skew.maxis,Kurt.maxis,Kurt.Maxis,Holl.Ra,Class
0,95,48,83,178,72,10,162,42,20,159,176,379,184,70,6,16,187,197,van
1,91,41,84,141,57,9,149,45,19,143,170,330,158,72,9,14,189,199,van
2,104,50,106,209,66,10,207,32,23,158,223,635,220,73,14,9,188,196,saab
3,93,41,82,159,63,9,144,46,19,143,160,309,127,63,6,10,199,207,van
4,85,44,70,205,103,52,149,45,19,144,241,325,188,127,9,11,180,183,bus

In [4]:
X,y = vehicle.drop('Class', axis = 1), vehicle.Class
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=.3,random_state=26,stratify=y)

In [5]:
cs=np.linspace(.001,10,20)
scaler=StandardScaler()
dfs=['ovo','ovr']
scores=[]
for c in tqdm(cs):
    for f in dfs:
        svm = SVC(kernel='linear',C=c,decision_function_shape=f)
        pipe=Pipeline([('sc',scaler),('svm',svm)])
        pipe.fit(X_train, y_train)
        pred = pipe.predict(X_test)
        scores.append([c,f,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['C','Decision','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)[:20]

100%|██████████| 20/20 [00:01<00:00, 11.32it/s]

           C Decision    scores
0   2.632316      ovr  0.807087
1   2.632316      ovo  0.807087
2   3.684842      ovo  0.807087
3   3.684842      ovr  0.807087
4   2.106053      ovr  0.807087
5   2.106053      ovo  0.807087
6   1.579789      ovo  0.803150
7   1.579789      ovr  0.803150
8   6.316158      ovo  0.803150
9   6.316158      ovr  0.803150
10  4.737368      ovo  0.803150
11  4.737368      ovr  0.803150
12  5.263632      ovo  0.803150
13  5.263632      ovr  0.803150
14  3.158579      ovr  0.803150
15  3.158579      ovo  0.803150
16  4.211105      ovo  0.803150
17  4.211105      ovr  0.803150
18  5.789895      ovo  0.803150
19  5.789895      ovr  0.803150

In [7]:
cs=np.linspace(.001,10,20)
gs = np.linspace(.01,10,5)
scaler=StandardScaler()
dfs=['ovo','ovr']
scores=[]
for c in tqdm(cs):
    for f in dfs:
        for g in gs:
            svm = SVC(kernel='rbf',C=c, gamma=g,decision_function_shape=f)
            pipe=Pipeline([('sc',scaler),('svm',svm)])
            pipe.fit(X_train, y_train)
            pred = pipe.predict(X_test)
            scores.append([c,g,f,accuracy_score(y_test, pred)])
df_score=pd.DataFrame(scores,columns=['C','Gamma','Decision','scores'])
df_score.sort_values('scores',ascending=False,ignore_index=True)

100%|██████████| 20/20 [00:12<00:00,  1.56it/s]

             C    Gamma Decision    scores
0    10.000000   0.0100      ovo  0.807087
1    10.000000   0.0100      ovr  0.807087
2     9.473737   0.0100      ovr  0.803150
3     9.473737   0.0100      ovo  0.803150
4     5.789895   0.0100      ovo  0.803150
..         ...      ...      ...       ...
195   0.001000   7.5025      ovo  0.255906
196   0.001000  10.0000      ovo  0.255906
197   0.001000   0.0100      ovr  0.255906
198   0.001000   2.5075      ovr  0.255906
199   0.001000   5.0050      ovr  0.255906

[200 rows x 4 columns]